version: "3.7"
services:
  node:
    build: .
    container_name: node-container
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - backend
    depends_on:
      - mongo

  mongo:
    build:
      context: .
      dockerfile: dockerfile-mongo
    container_name: mongo-container
    restart: always
    ports:
      - "27017:27017"
    networks:
      - backend

  nginx:
    build:
      context: .
      dockerfile: dockerfile-nginx
    container_name: nginx-container
    restart: always
    ports:
      - "80:80"
    networks:
      - backend
    links:
      - "node:server"

networks:
  backend:
    driver: "bridge"