version: "3.7"
services:
  node:
    build: .
    container_name: node-container
    restart: always
    ports:
      - "3000:3000"
    networks:
      - backend

  nginx:
    build:
      context: .
      dockerfile: dockerfile-nginx
    container_name: nginx-container
    restart: always
    ports:
      - "80:80"
    networks:
      - backend
    links:
      - "node:server"

networks:
  backend:
    driver: "bridge"